In [120]:
import pandas as pd

In [121]:
df = pd.read_csv("superhero_powers.csv")
df

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Yellowjacket II,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
663,Ymir,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
664,Yoda,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
665,Zatanna,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
666,Zoom,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [122]:
s = pd.Series([1,2,3,4,5,6,7])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [123]:
index_day = ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
data = [1,2,3,4,5,6,7]

In [124]:
s = pd.Series(data,index = index_day)
s

monday       1
tuesday      2
wednesday    3
thursday     4
friday       5
saturday     6
sunday       7
dtype: int64

In [125]:
s.mean()

np.float64(4.0)

In [126]:
4*s

monday        4
tuesday       8
wednesday    12
thursday     16
friday       20
saturday     24
sunday       28
dtype: int64

In [127]:
df = pd.DataFrame({"first":s,"second":s*2,"third":s*5})
df

           first  second  third
monday         1       2      5
tuesday        2       4     10
wednesday      3       6     15
thursday       4       8     20
friday         5      10     25
saturday       6      12     30
sunday         7      14     35

In [128]:
column_names = ['city','population']
index_country = ['japan','india','china','brazil','mexico']

In [129]:
row1 = ['tokyo',37.4]
row2 = ['delhi',28.5]
row3 = ['shangai',27.5]
row4 = ['sau palio',21.5]
row5 = ['mexico city',21.6]
data = [row1,row2,row3,row4,row5]

In [130]:
df = pd.DataFrame(data,index = index_country,columns = column_names)
df

               city  population
japan         tokyo        37.4
india         delhi        28.5
china       shangai        27.5
brazil    sau palio        21.5
mexico  mexico city        21.6

In [131]:
cities = ['tokyo','mumbai','shangai','rio','mexico city']
population = [28.5,25.6,45.5,23.5,54.2]
popu_dict = {'city':cities,"population":population}

In [132]:
df = pd.DataFrame(popu_dict,index = index_country)
df

               city  population
japan         tokyo        28.5
india        mumbai        25.6
china       shangai        45.5
brazil          rio        23.5
mexico  mexico city        54.2

In [133]:
hero_dc = pd.read_excel('superhero_info.xlsx',sheet_name = 'DC Comics')
hero_marvel = pd.read_excel('superhero_info.xlsx',sheet_name = 'Marvel Comics')

In [134]:
hero_marvel.head()

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Alignment,Weight
0,A-Bomb,Male,yellow,Human,No Hair,203,Marvel Comics,good,441
1,Abomination,Male,green,Human / Radiation,No Hair,203,Marvel Comics,bad,441
2,Abraxas,Male,blue,Cosmic Entity,Black,-99,Marvel Comics,bad,-99
3,Absorbing Man,Male,blue,Human,No Hair,193,Marvel Comics,bad,122
4,Agent 13,Female,blue,-,Blond,173,Marvel Comics,good,61

In [135]:
df = pd.read_csv('weather.csv')
df

,date,temperature_high,temperature_low,rained,snowed,overcast,comments
0,2021-01-01,4.0,1,1,False,cloudy,happy new year
1,2021-01-02,11.0,2,0,False,sunny,second day
2,2021-01-03,3.0,2,0,False,foggy,third day
3,2021-01-04,6.0,2,0,False,sunny,first business day
4,2021-01-05,4.0,unknown,0,False,cloudy,second business day

In [136]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      float64
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      int64
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 377.0 bytes

In [137]:
df['temperature_high'] = df['temperature_high'].astype('int8')

In [138]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      int64
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(1), int64(1), int8(1), str(4)
memory usage: 342.0 bytes

In [140]:
df['rained'] = df['rained'].astype('bool')
df['rained']

0     True
1    False
2    False
3    False
4    False
Name: rained, dtype: bool

In [142]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      bool
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(2), int8(1), str(4)
memory usage: 307.0 bytes

In [143]:
df['overcast']

0    cloudy
1     sunny
2     foggy
3     sunny
4    cloudy
Name: overcast, dtype: str

In [144]:
df['temperature_low'] = pd.to_numeric(df['temperature_low'],errors = 'coerce')

In [146]:
df['temperature_low']

0    1.0
1    2.0
2    2.0
3    2.0
4    NaN
Name: temperature_low, dtype: float64

In [147]:
df['date'] = pd.to_datetime(df['date'])

In [148]:
df['date']

0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-04
4   2021-01-05
Name: date, dtype: datetime64[us]

In [149]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      datetime64[us]
 1   temperature_high  5 non-null      int8
 2   temperature_low   4 non-null      float64
 3   rained            5 non-null      bool
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(2), datetime64[us](1), float64(1), int8(1), str(2)
memory usage: 307.0 bytes

In [150]:
hero_powers.info()

NameError: name 'hero_powers' is not defined